mutation CreateOrderItem(
  $totalPrice: Int
  $isDelivery: Boolean
  $name: String
  $phone: String
  $address: String
  $comment: String
) {
  create_orders_item(
    data: {
      totalPrice: $totalPrice
      isDelivery: $isDelivery
      name: $name
      phone: $phone
      address: $address
      comment: $comment
    }
  ) {
    id
    totalPrice
    isDelivery

    name
    phone
    address

    comment
  }
}
