query GetOrderById($id: ID!) {
  orders_by_id(id: $id) {
    id
    totalPrice
    isDelivery
    name
    phone
    basket {
      count
      name
      totalPrice
      modificators
    }

    address
    comment
  }
}
